import json
import sys
from sqlalchemy import text
from database import engine, SessionLocal, Base
from models import Problem

def import_open_source_problems():
    print("=" * 60)
    print("LOADING 50+ OPEN-SOURCE LEETCODE PROBLEMS FOR RANKED DUELS")
    print("=" * 60)

    db = SessionLocal()
    try:
        Base.metadata.create_all(bind=engine)

        dataset = [
            # 1 - 20
            {"id": 1, "title": "Two Sum", "difficulty": "Easy", "topics": ["Array", "Hash Table"], "acceptance": 49.2, "description": "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.", "input_format": "Array nums, target int", "output_format": "Array of 2 indices", "constraints": ["2 <= nums.length <= 10^4"], "examples": [{"input": "nums = [2, 7, 11, 15], target = 9", "output": "[0, 1]"}], "starter_code": "function twoSum(nums, target) {\n  \n}", "order_matters": False, "param_types": ["array", "number"], "return_type": "array"},
            {"id": 2, "title": "Valid Parentheses", "difficulty": "Easy", "topics": ["Stack", "String"], "acceptance": 40.1, "description": "Given a string s containing '()[]{}', determine if the input string is valid.", "input_format": "String s", "output_format": "Boolean", "constraints": ["1 <= s.length <= 10^4"], "examples": [{"input": "s = \"()\"", "output": "true"}, {"input": "s = \"(]\"", "output": "false"}], "starter_code": "function isValid(s) {\n  \n}", "order_matters": True, "param_types": ["string"], "return_type": "boolean"},
            {"id": 3, "title": "Reverse Linked List", "difficulty": "Easy", "topics": ["Linked List"], "acceptance": 72.5, "description": "Reverse a singly linked list and return its head.", "input_format": "Head of linked list", "output_format": "Head of reversed list", "constraints": ["0 <= nodes <= 5000"], "examples": [{"input": "head = [1, 2, 3, 4, 5]", "output": "[5, 4, 3, 2, 1]"}], "starter_code": "function reverseList(head) {\n  \n}", "order_matters": True, "param_types": ["linked_list"], "return_type": "linked_list"},
            {"id": 4, "title": "Climbing Stairs", "difficulty": "Easy", "topics": ["Dynamic Programming"], "acceptance": 51.3, "description": "Takes n steps to reach the top. Each time climb 1 or 2 steps. Return number of distinct ways.", "input_format": "Integer n", "output_format": "Integer ways", "constraints": ["1 <= n <= 45"], "examples": [{"input": "n = 2", "output": "2"}, {"input": "n = 3", "output": "3"}], "starter_code": "function climbStairs(n) {\n  \n}", "order_matters": True, "param_types": ["number"], "return_type": "number"},
            {"id": 5, "title": "Maximum Subarray", "difficulty": "Medium", "topics": ["Array", "Dynamic Programming"], "acceptance": 50.1, "description": "Find the contiguous subarray with the largest sum and return its sum.", "input_format": "Array nums", "output_format": "Integer max sum", "constraints": ["1 <= nums.length <= 10^5"], "examples": [{"input": "nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]", "output": "6"}], "starter_code": "function maxSubArray(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 6, "title": "Palindrome Number", "difficulty": "Easy", "topics": ["Math"], "acceptance": 53.8, "description": "Return true if x is a palindrome integer.", "input_format": "Integer x", "output_format": "Boolean", "constraints": ["-2^31 <= x <= 2^31 - 1"], "examples": [{"input": "x = 121", "output": "true"}, {"input": "x = -121", "output": "false"}], "starter_code": "function isPalindrome(x) {\n  \n}", "order_matters": True, "param_types": ["number"], "return_type": "boolean"},
            {"id": 7, "title": "Merge Intervals", "difficulty": "Medium", "topics": ["Array", "Sorting"], "acceptance": 46.2, "description": "Merge all overlapping intervals.", "input_format": "2D Array of intervals", "output_format": "2D Array of merged intervals", "constraints": ["1 <= intervals.length <= 10^4"], "examples": [{"input": "intervals = [[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]"}], "starter_code": "function merge(intervals) {\n  \n}", "order_matters": True, "param_types": ["matrix"], "return_type": "matrix"},
            {"id": 8, "title": "Product of Array Except Self", "difficulty": "Medium", "topics": ["Array", "Prefix Sum"], "acceptance": 64.8, "description": "Return array answer such that answer[i] is equal to product of all elements except nums[i].", "input_format": "Array nums", "output_format": "Array products", "constraints": ["2 <= nums.length <= 10^5"], "examples": [{"input": "nums = [1, 2, 3, 4]", "output": "[24, 12, 8, 6]"}], "starter_code": "function productExceptSelf(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "array"},
            {"id": 9, "title": "Valid Anagram", "difficulty": "Easy", "topics": ["String", "Hash Table"], "acceptance": 63.2, "description": "Return true if t is an anagram of s.", "input_format": "Strings s and t", "output_format": "Boolean", "constraints": ["1 <= s.length <= 5 * 10^4"], "examples": [{"input": "s = \"anagram\", t = \"nagaram\"", "output": "true"}], "starter_code": "function isAnagram(s, t) {\n  \n}", "order_matters": True, "param_types": ["string", "string"], "return_type": "boolean"},
            {"id": 10, "title": "Number of Islands", "difficulty": "Medium", "topics": ["DFS", "BFS", "Matrix"], "acceptance": 56.4, "description": "Return number of islands in 2D binary grid.", "input_format": "2D Matrix grid", "output_format": "Integer count", "constraints": ["1 <= m, n <= 300"], "examples": [{"input": "grid = [[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]]", "output": "1"}], "starter_code": "function numIslands(grid) {\n  \n}", "order_matters": True, "param_types": ["matrix"], "return_type": "number"},
            {"id": 11, "title": "Binary Search", "difficulty": "Easy", "topics": ["Binary Search"], "acceptance": 56.1, "description": "Search target in sorted nums. Return index or -1.", "input_format": "Sorted array nums, target int", "output_format": "Integer index", "constraints": ["1 <= nums.length <= 10^4"], "examples": [{"input": "nums = [-1, 0, 3, 5, 9, 12], target = 9", "output": "4"}], "starter_code": "function search(nums, target) {\n  \n}", "order_matters": True, "param_types": ["array", "number"], "return_type": "number"},
            {"id": 12, "title": "Binary Tree Level Order Traversal", "difficulty": "Medium", "topics": ["Tree", "BFS"], "acceptance": 62.1, "description": "Return level order traversal of binary tree nodes' values.", "input_format": "Root of binary tree", "output_format": "2D Array of levels", "constraints": ["0 <= nodes <= 2000"], "examples": [{"input": "root = [3, 9, 20, null, null, 15, 7]", "output": "[[3],[9,20],[15,7]]"}], "starter_code": "function levelOrder(root) {\n  \n}", "order_matters": True, "param_types": ["binary_tree"], "return_type": "matrix"},
            {"id": 13, "title": "Invert Binary Tree", "difficulty": "Easy", "topics": ["Tree", "DFS"], "acceptance": 75.2, "description": "Invert binary tree and return root.", "input_format": "Root of binary tree", "output_format": "Inverted root", "constraints": ["0 <= nodes <= 100"], "examples": [{"input": "root = [4, 2, 7, 1, 3, 6, 9]", "output": "[4, 7, 2, 9, 6, 3, 1]"}], "starter_code": "function invertTree(root) {\n  \n}", "order_matters": True, "param_types": ["binary_tree"], "return_type": "binary_tree"},
            {"id": 14, "title": "Maximum Depth of Binary Tree", "difficulty": "Easy", "topics": ["Tree", "DFS"], "acceptance": 74.1, "description": "Return maximum depth of binary tree.", "input_format": "Root of binary tree", "output_format": "Integer depth", "constraints": ["0 <= nodes <= 10^4"], "examples": [{"input": "root = [3, 9, 20, null, null, 15, 7]", "output": "3"}], "starter_code": "function maxDepth(root) {\n  \n}", "order_matters": True, "param_types": ["binary_tree"], "return_type": "number"},
            {"id": 15, "title": "Merge Two Sorted Lists", "difficulty": "Easy", "topics": ["Linked List"], "acceptance": 62.4, "description": "Merge two sorted linked lists into one sorted list.", "input_format": "Heads list1 and list2", "output_format": "Merged list head", "constraints": ["0 <= nodes <= 50"], "examples": [{"input": "list1 = [1, 2, 4], list2 = [1, 3, 4]", "output": "[1, 1, 2, 3, 4, 4]"}], "starter_code": "function mergeTwoLists(list1, list2) {\n  \n}", "order_matters": True, "param_types": ["linked_list", "linked_list"], "return_type": "linked_list"},
            {"id": 16, "title": "Reverse String", "difficulty": "Easy", "topics": ["Two Pointers", "String"], "acceptance": 77.1, "description": "Reverse character array in-place.", "input_format": "Array of chars s", "output_format": "Void", "constraints": ["1 <= s.length <= 10^5"], "examples": [{"input": "s = [\"h\",\"e\",\"l\",\"l\",\"o\"]", "output": "[\"o\",\"l\",\"l\",\"e\",\"h\"]"}], "starter_code": "function reverseString(s) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "void", "is_mutation": True, "mutate_arg": 0},
            {"id": 17, "title": "Group Anagrams", "difficulty": "Medium", "topics": ["String", "Hash Table"], "acceptance": 66.8, "description": "Group anagrams together from array of strings.", "input_format": "Array of strings", "output_format": "2D Array of grouped anagrams", "constraints": ["1 <= strs.length <= 10^4"], "examples": [{"input": "strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]"}], "starter_code": "function groupAnagrams(strs) {\n  \n}", "order_matters": False, "param_types": ["array"], "return_type": "matrix"},
            {"id": 18, "title": "Container With Most Water", "difficulty": "Medium", "topics": ["Two Pointers", "Array"], "acceptance": 54.3, "description": "Find two lines that form container with most water.", "input_format": "Array height", "output_format": "Integer max area", "constraints": ["2 <= height.length <= 10^5"], "examples": [{"input": "height = [1, 8, 6, 2, 5, 4, 8, 3, 7]", "output": "49"}], "starter_code": "function maxArea(height) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 19, "title": "Best Time to Buy and Sell Stock", "difficulty": "Easy", "topics": ["Array", "Dynamic Programming"], "acceptance": 54.1, "description": "Maximize profit buying on 1 day and selling in future.", "input_format": "Array prices", "output_format": "Integer max profit", "constraints": ["1 <= prices.length <= 10^5"], "examples": [{"input": "prices = [7, 1, 5, 3, 6, 4]", "output": "5"}], "starter_code": "function maxProfit(prices) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 20, "title": "Longest Substring Without Repeating Characters", "difficulty": "Medium", "topics": ["String", "Sliding Window"], "acceptance": 33.8, "description": "Find length of longest substring without repeating chars.", "input_format": "String s", "output_format": "Integer length", "constraints": ["0 <= s.length <= 5 * 10^4"], "examples": [{"input": "s = \"abcabcbb\"", "output": "3"}], "starter_code": "function lengthOfLongestSubstring(s) {\n  \n}", "order_matters": True, "param_types": ["string"], "return_type": "number"},

            # 21 - 55 NEW POPULATED PROBLEMS
            {"id": 21, "title": "3Sum", "difficulty": "Medium", "topics": ["Array", "Two Pointers"], "acceptance": 32.5, "description": "Return all unique triplets [nums[i], nums[j], nums[k]] such that i != j != k and sum is 0.", "input_format": "Array nums", "output_format": "2D Array of triplets", "constraints": ["3 <= nums.length <= 3000"], "examples": [{"input": "nums = [-1, 0, 1, 2, -1, -4]", "output": "[[-1, -1, 2], [-1, 0, 1]]"}], "starter_code": "function threeSum(nums) {\n  \n}", "order_matters": False, "param_types": ["array"], "return_type": "matrix"},
            {"id": 22, "title": "Search in Rotated Sorted Array", "difficulty": "Medium", "topics": ["Array", "Binary Search"], "acceptance": 39.4, "description": "Given sorted rotated array nums and target, return index of target or -1.", "input_format": "Array nums, target int", "output_format": "Integer index", "constraints": ["1 <= nums.length <= 5000"], "examples": [{"input": "nums = [4, 5, 6, 7, 0, 1, 2], target = 0", "output": "4"}], "starter_code": "function search(nums, target) {\n  \n}", "order_matters": True, "param_types": ["array", "number"], "return_type": "number"},
            {"id": 23, "title": "Find Minimum in Rotated Sorted Array", "difficulty": "Medium", "topics": ["Array", "Binary Search"], "acceptance": 49.1, "description": "Given sorted rotated array nums of unique elements, return minimum element.", "input_format": "Array nums", "output_format": "Integer min", "constraints": ["1 <= nums.length <= 5000"], "examples": [{"input": "nums = [3, 4, 5, 1, 2]", "output": "1"}], "starter_code": "function findMin(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 24, "title": "Same Tree", "difficulty": "Easy", "topics": ["Tree", "DFS"], "acceptance": 58.0, "description": "Given roots of two binary trees p and q, check if they are the same.", "input_format": "Roots p and q", "output_format": "Boolean", "constraints": ["0 <= nodes <= 100"], "examples": [{"input": "p = [1, 2, 3], q = [1, 2, 3]", "output": "true"}], "starter_code": "function isSameTree(p, q) {\n  \n}", "order_matters": True, "param_types": ["binary_tree", "binary_tree"], "return_type": "boolean"},
            {"id": 25, "title": "Subtree of Another Tree", "difficulty": "Easy", "topics": ["Tree", "DFS"], "acceptance": 46.5, "description": "Check if subTree is a subtree of root tree.", "input_format": "Roots root and subTree", "output_format": "Boolean", "constraints": ["1 <= nodes <= 2000"], "examples": [{"input": "root = [3, 4, 5, 1, 2], subTree = [4, 1, 2]", "output": "true"}], "starter_code": "function isSubtree(root, subTree) {\n  \n}", "order_matters": True, "param_types": ["binary_tree", "binary_tree"], "return_type": "boolean"},
            {"id": 26, "title": "Lowest Common Ancestor of BST", "difficulty": "Medium", "topics": ["Tree", "DFS", "BST"], "acceptance": 60.5, "description": "Find lowest common ancestor (LCA) node of two given nodes in BST.", "input_format": "Root root, ints p and q", "output_format": "Integer LCA val", "constraints": ["2 <= nodes <= 10^5"], "examples": [{"input": "root = [6, 2, 8, 0, 4, 7, 9], p = 2, q = 8", "output": "6"}], "starter_code": "function lowestCommonAncestor(root, p, q) {\n  \n}", "order_matters": True, "param_types": ["binary_tree", "number", "number"], "return_type": "number"},
            {"id": 27, "title": "Remove Nth Node From End of List", "difficulty": "Medium", "topics": ["Linked List", "Two Pointers"], "acceptance": 42.1, "description": "Remove nth node from end of linked list and return its head.", "input_format": "Head head, integer n", "output_format": "Head of modified list", "constraints": ["1 <= sz <= 30"], "examples": [{"input": "head = [1, 2, 3, 4, 5], n = 2", "output": "[1, 2, 3, 5]"}], "starter_code": "function removeNthFromEnd(head, n) {\n  \n}", "order_matters": True, "param_types": ["linked_list", "number"], "return_type": "linked_list"},
            {"id": 28, "title": "Linked List Cycle", "difficulty": "Easy", "topics": ["Linked List", "Two Pointers"], "acceptance": 48.0, "description": "Return true if linked list has a cycle.", "input_format": "Head head", "output_format": "Boolean", "constraints": ["0 <= nodes <= 10^4"], "examples": [{"input": "head = [3, 2, 0, -4]", "output": "false"}], "starter_code": "function hasCycle(head) {\n  \n}", "order_matters": True, "param_types": ["linked_list"], "return_type": "boolean"},
            {"id": 29, "title": "Find the Duplicate Number", "difficulty": "Medium", "topics": ["Array", "Two Pointers", "Binary Search"], "acceptance": 59.2, "description": "Given array of n + 1 ints where each int is in range [1, n], return duplicate number without modifying array.", "input_format": "Array nums", "output_format": "Integer duplicate", "constraints": ["1 <= n <= 10^5"], "examples": [{"input": "nums = [1, 3, 4, 2, 2]", "output": "2"}], "starter_code": "function findDuplicate(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 30, "title": "Top K Frequent Elements", "difficulty": "Medium", "topics": ["Array", "Hash Table", "Bucket Sort"], "acceptance": 64.0, "description": "Given integer array nums and integer k, return k most frequent elements.", "input_format": "Array nums, int k", "output_format": "Array of k elements", "constraints": ["1 <= nums.length <= 10^5"], "examples": [{"input": "nums = [1, 1, 1, 2, 2, 3], k = 2", "output": "[1, 2]"}], "starter_code": "function topKFrequent(nums, k) {\n  \n}", "order_matters": False, "param_types": ["array", "number"], "return_type": "array"},
            {"id": 31, "title": "Longest Consecutive Sequence", "difficulty": "Medium", "topics": ["Array", "Hash Table"], "acceptance": 47.5, "description": "Given unsorted array nums, return length of longest consecutive elements sequence in O(n) time.", "input_format": "Array nums", "output_format": "Integer length", "constraints": ["0 <= nums.length <= 10^5"], "examples": [{"input": "nums = [100, 4, 200, 1, 3, 2]", "output": "4"}], "starter_code": "function longestConsecutive(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 32, "title": "Valid Palindrome", "difficulty": "Easy", "topics": ["Two Pointers", "String"], "acceptance": 45.0, "description": "Convert all uppercase letters into lowercase and remove non-alphanumeric chars. Check if palindrome.", "input_format": "String s", "output_format": "Boolean", "constraints": ["1 <= s.length <= 2 * 10^5"], "examples": [{"input": "s = \"A man, a plan, a canal: Panama\"", "output": "true"}], "starter_code": "function isPalindrome(s) {\n  \n}", "order_matters": True, "param_types": ["string"], "return_type": "boolean"},
            {"id": 33, "title": "Search a 2D Matrix", "difficulty": "Medium", "topics": ["Array", "Binary Search", "Matrix"], "acceptance": 48.2, "description": "Write efficient algorithm searching target in m x n matrix where rows & columns are sorted.", "input_format": "2D Matrix matrix, target int", "output_format": "Boolean", "constraints": ["1 <= m, n <= 100"], "examples": [{"input": "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3", "output": "true"}], "starter_code": "function searchMatrix(matrix, target) {\n  \n}", "order_matters": True, "param_types": ["matrix", "number"], "return_type": "boolean"},
            {"id": 34, "title": "House Robber", "difficulty": "Medium", "topics": ["Dynamic Programming"], "acceptance": 49.8, "description": "Determine maximum money you can rob tonight without robbing adjacent houses.", "input_format": "Array nums", "output_format": "Integer max money", "constraints": ["1 <= nums.length <= 100"], "examples": [{"input": "nums = [1, 2, 3, 1]", "output": "4"}], "starter_code": "function rob(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 35, "title": "House Robber II", "difficulty": "Medium", "topics": ["Dynamic Programming"], "acceptance": 41.2, "description": "Houses arranged in a circle. Maximize robbed money without robbing adjacent houses.", "input_format": "Array nums", "output_format": "Integer max money", "constraints": ["1 <= nums.length <= 100"], "examples": [{"input": "nums = [2, 3, 2]", "output": "3"}], "starter_code": "function rob(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"},
            {"id": 36, "title": "Coin Change", "difficulty": "Medium", "topics": ["Dynamic Programming", "BFS"], "acceptance": 42.0, "description": "Return fewest number of coins needed to make up amount. If impossible, return -1.", "input_format": "Array coins, int amount", "output_format": "Integer count", "constraints": ["1 <= coins.length <= 12"], "examples": [{"input": "coins = [1, 2, 5], amount = 11", "output": "3"}], "starter_code": "function coinChange(coins, amount) {\n  \n}", "order_matters": True, "param_types": ["array", "number"], "return_type": "number"},
            {"id": 37, "title": "Word Break", "difficulty": "Medium", "topics": ["Hash Table", "Dynamic Programming", "Trie"], "acceptance": 46.1, "description": "Return true if string s can be segmented into space-separated dictionary words.", "input_format": "String s, Array wordDict", "output_format": "Boolean", "constraints": ["1 <= s.length <= 300"], "examples": [{"input": "s = \"leetcode\", wordDict = [\"leet\", \"code\"]", "output": "true"}], "starter_code": "function wordBreak(s, wordDict) {\n  \n}", "order_matters": True, "param_types": ["string", "array"], "return_type": "boolean"},
            {"id": 38, "title": "Longest Palindromic Substring", "difficulty": "Medium", "topics": ["String", "Dynamic Programming"], "acceptance": 32.6, "description": "Given string s, return longest palindromic substring in s.", "input_format": "String s", "output_format": "String palindrome", "constraints": ["1 <= s.length <= 1000"], "examples": [{"input": "s = \"babad\"", "output": "\"bab\""}], "starter_code": "function longestPalindrome(s) {\n  \n}", "order_matters": True, "param_types": ["string"], "return_type": "string"},
            {"id": 39, "title": "Palindromic Substrings", "difficulty": "Medium", "topics": ["String", "Dynamic Programming"], "acceptance": 67.2, "description": "Given string s, return number of palindromic substrings in s.", "input_format": "String s", "output_format": "Integer count", "constraints": ["1 <= s.length <= 1000"], "examples": [{"input": "s = \"abc\"", "output": "3"}, {"input": "s = \"aaa\"", "output": "6"}], "starter_code": "function countSubstrings(s) {\n  \n}", "order_matters": True, "param_types": ["string"], "return_type": "number"},
            {"id": 40, "title": "Daily Temperatures", "difficulty": "Medium", "topics": ["Array", "Stack", "Monotonic Stack"], "acceptance": 66.1, "description": "Return array answer where answer[i] is number of days to wait after ith day for warmer temp.", "input_format": "Array temperatures", "output_format": "Array days", "constraints": ["1 <= temperatures.length <= 10^5"], "examples": [{"input": "temperatures = [73, 74, 75, 71, 69, 72, 76, 73]", "output": "[1, 1, 4, 2, 1, 1, 0, 0]"}], "starter_code": "function dailyTemperatures(temperatures) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "array"},
            {"id": 41, "title": "Kth Largest Element in an Array", "difficulty": "Medium", "topics": ["Array", "Divide and Conquer", "Quickselect"], "acceptance": 66.2, "description": "Given integer array nums and integer k, return kth largest element in array.", "input_format": "Array nums, int k", "output_format": "Integer kth largest", "constraints": ["1 <= k <= nums.length <= 10^5"], "examples": [{"input": "nums = [3, 2, 1, 5, 6, 4], k = 2", "output": "5"}], "starter_code": "function findKthLargest(nums, k) {\n  \n}", "order_matters": True, "param_types": ["array", "number"], "return_type": "number"},
            {"id": 42, "title": "Sort Colors", "difficulty": "Medium", "topics": ["Array", "Two Pointers", "Sorting"], "acceptance": 59.1, "description": "Sort array of red, white, blue colors in-place represented by ints 0, 1, 2.", "input_format": "Array nums", "output_format": "Void", "constraints": ["1 <= nums.length <= 300"], "examples": [{"input": "nums = [2, 0, 2, 1, 1, 0]", "output": "[0, 0, 1, 1, 2, 2]"}], "starter_code": "function sortColors(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "void", "is_mutation": True, "mutate_arg": 0},
            {"id": 43, "title": "Subarray Sum Equals K", "difficulty": "Medium", "topics": ["Array", "Hash Table", "Prefix Sum"], "acceptance": 43.8, "description": "Given array of ints nums and int k, return total number of subarrays whose sum equals k.", "input_format": "Array nums, int k", "output_format": "Integer count", "constraints": ["1 <= nums.length <= 2 * 10^4"], "examples": [{"input": "nums = [1, 1, 1], k = 2", "output": "2"}], "starter_code": "function subarraySum(nums, k) {\n  \n}", "order_matters": True, "param_types": ["array", "number"], "return_type": "number"},
            {"id": 44, "title": "Validate Binary Search Tree", "difficulty": "Medium", "topics": ["Tree", "DFS", "BST"], "acceptance": 32.1, "description": "Determine if given binary tree root is a valid Binary Search Tree.", "input_format": "Root of binary tree", "output_format": "Boolean", "constraints": ["1 <= nodes <= 10^4"], "examples": [{"input": "root = [2, 1, 3]", "output": "true"}, {"input": "root = [5, 1, 4, null, null, 3, 6]", "output": "false"}], "starter_code": "function isValidBST(root) {\n  \n}", "order_matters": True, "param_types": ["binary_tree"], "return_type": "boolean"},
            {"id": 45, "title": "Kth Smallest Element in a BST", "difficulty": "Medium", "topics": ["Tree", "DFS", "BST"], "acceptance": 70.2, "description": "Given root of BST and integer k, return kth smallest value of all nodes in tree.", "input_format": "Root root, int k", "output_format": "Integer kth smallest", "constraints": ["1 <= k <= nodes <= 10^4"], "examples": [{"input": "root = [3, 1, 4, null, 2], k = 1", "output": "1"}], "starter_code": "function kthSmallest(root, k) {\n  \n}", "order_matters": True, "param_types": ["binary_tree", "number"], "return_type": "number"},
            {"id": 46, "title": "Construct Binary Tree from Preorder and Inorder Traversal", "difficulty": "Medium", "topics": ["Tree", "Array", "Hash Table", "Divide and Conquer"], "acceptance": 61.8, "description": "Given two integer arrays preorder and inorder, construct and return binary tree.", "input_format": "Array preorder, Array inorder", "output_format": "Root of constructed tree", "constraints": ["1 <= nodes <= 3000"], "examples": [{"input": "preorder = [3, 9, 20, 15, 7], inorder = [9, 3, 15, 20, 7]", "output": "[3, 9, 20, null, null, 15, 7]"}], "starter_code": "function buildTree(preorder, inorder) {\n  \n}", "order_matters": True, "param_types": ["array", "array"], "return_type": "binary_tree"},
            {"id": 47, "title": "Course Schedule", "difficulty": "Medium", "topics": ["DFS", "BFS", "Graph", "Topological Sort"], "acceptance": 45.4, "description": "There are total numCourses courses. Given prerequisites array, check if you can finish all courses.", "input_format": "Integer numCourses, 2D Array prerequisites", "output_format": "Boolean", "constraints": ["1 <= numCourses <= 2000"], "examples": [{"input": "numCourses = 2, prerequisites = [[1, 0]]", "output": "true"}], "starter_code": "function canFinish(numCourses, prerequisites) {\n  \n}", "order_matters": True, "param_types": ["number", "matrix"], "return_type": "boolean"},
            {"id": 48, "title": "Pacific Atlantic Water Flow", "difficulty": "Medium", "topics": ["Array", "DFS", "BFS", "Matrix"], "acceptance": 54.2, "description": "Find list of grid coordinates where water can flow to both Pacific and Atlantic oceans.", "input_format": "2D Matrix heights", "output_format": "2D Array of coordinates", "constraints": ["1 <= m, n <= 200"], "examples": [{"input": "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", "output": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]"}], "starter_code": "function pacificAtlantic(heights) {\n  \n}", "order_matters": False, "param_types": ["matrix"], "return_type": "matrix"},
            {"id": 49, "title": "Graph Valid Tree", "difficulty": "Medium", "topics": ["DFS", "BFS", "Graph", "Union Find"], "acceptance": 47.1, "description": "Given n nodes labeled 0 to n - 1 and list of undirected edges, check if edges form valid tree.", "input_format": "Integer n, 2D Array edges", "output_format": "Boolean", "constraints": ["1 <= n <= 2000"], "examples": [{"input": "n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]", "output": "true"}], "starter_code": "function validTree(n, edges) {\n  \n}", "order_matters": True, "param_types": ["number", "matrix"], "return_type": "boolean"},
            {"id": 50, "title": "Missing Number", "difficulty": "Easy", "topics": ["Array", "Math", "Bit Manipulation"], "acceptance": 62.9, "description": "Given array nums containing n distinct numbers in range [0, n], return the only number missing.", "input_format": "Array nums", "output_format": "Integer missing", "constraints": ["n == nums.length <= 10^4"], "examples": [{"input": "nums = [3, 0, 1]", "output": "2"}], "starter_code": "function missingNumber(nums) {\n  \n}", "order_matters": True, "param_types": ["array"], "return_type": "number"}
        ]

        added_count = 0
        updated_count = 0

        for p_data in dataset:
            pid = p_data["id"]
            existing = db.query(Problem).filter(Problem.id == pid).first()
            if existing:
                existing.title = p_data["title"]
                existing.difficulty = p_data["difficulty"]
                existing.topics = p_data["topics"]
                existing.acceptance = p_data["acceptance"]
                existing.description = p_data["description"]
                existing.input_format = p_data["input_format"]
                existing.output_format = p_data["output_format"]
                existing.constraints = p_data["constraints"]
                existing.examples = json.dumps(p_data["examples"])
                existing.starter_code = p_data["starter_code"]
                existing.order_matters = p_data["order_matters"]
                existing.param_types = p_data["param_types"]
                existing.return_type = p_data["return_type"]
                existing.is_mutation = p_data.get("is_mutation", False)
                existing.mutate_arg = p_data.get("mutate_arg", 0)
                updated_count += 1
            else:
                new_prob = Problem(
                    id=pid,
                    title=p_data["title"],
                    difficulty=p_data["difficulty"],
                    topics=p_data["topics"],
                    acceptance=p_data["acceptance"],
                    description=p_data["description"],
                    input_format=p_data["input_format"],
                    output_format=p_data["output_format"],
                    constraints=p_data["constraints"],
                    examples=json.dumps(p_data["examples"]),
                    starter_code=p_data["starter_code"],
                    order_matters=p_data["order_matters"],
                    param_types=p_data["param_types"],
                    return_type=p_data["return_type"],
                    is_mutation=p_data.get("is_mutation", False),
                    mutate_arg=p_data.get("mutate_arg", 0)
                )
                db.add(new_prob)
                added_count += 1

        db.commit()
        total_problems = db.query(Problem).count()
        print(f"[SUCCESS] Import completed!")
        print(f"          New problems added: {added_count}")
        print(f"          Existing updated:  {updated_count}")
        print(f"          Total DB problems: {total_problems}")

    except Exception as e:
        db.rollback()
        print(f"[ERROR] Import failed: {e}")
        sys.exit(1)
    finally:
        db.close()

if __name__ == "__main__":
    import_open_source_problems()
